apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: frankdev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhcnJpZmFuYWJlYWNoLmF6dXJlY3IuaW8iOiB7CgkJCSJhdXRoIjogIlpESmlZVE15T1RVdFpUaGlNeTAwWldFMExXSTRNMll0TVRCak1qTTRaV1prTVRnME9uVm9VemhSZms4dFowWm9VVzVYV1VRdVVsbEJibVZaUm1wYVEwMXdkVnBpVmtnM1dUVmlNMVk9IgoJCX0KCX0KfQ==
