resources:
  pipelines:
  - pipeline: DeployFrankiedevK8sDevelopment
    source: BuildFrankiedevK8sDevelopment
    project: Infrastructure
    trigger: true
  repositories:
  - repository: FrankiedevClusterDevelopmentBranch  # identifier (A-Z, a-z, 0-9, and underscore)
    type: github  # see the following "Type" topic
    name: fbarrento/website-k8s-tenant  # repository name (format depends on `type`)
    ref: cluster/development  # ref name to use; defaults to 'refs/heads/main'
    endpoint: fbarrento

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Deploy
    displayName: Deploy K8s Manifests to frankdev.io Development
    jobs:
    - deployment:
      environment: dev-K8s-sfihelv-kubeserver-d001
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo "FrankieDev.io Development Deploy after Build Artifacts"
            
            - checkout: FrankiedevClusterDevelopmentBranch
              persistCredentials: true

            - bash: |
                ls -la
                ls -la $(Build.ArtifactStagingDirectory)
              displayName: Checkout branch cluster/development

            - task: CopyFiles@2
              inputs:
                SourceFolder: $(Pipeline.Workspace)/DeployFrankiedevK8sDevelopment/MyBuildOutputs
                Contents: |
                  base/**/*
                  overlays/development/**/*
                OverWrite: true
                TargetFolder: $(Build.SourcesDirectory)

            - bash: |
                pwd
                cat /overlays/development/ingress.yaml
                git config --global user.email "francisco.barrento@gmail.com"
                git config --global user.name "Azure Pipeline Agent"
                git add .
                git commit -am"Deploying revision"
                git push origin HEAD:cluster/development

            


