resources:
  pipelines:
  - pipeline: DeployFrankiedevK8sDevelopment
    source: BuildFrankiedevK8sDevelopment
    project: Infrastructure
    trigger: true

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Deploy
    displayName: Deploy K8s Manifests to frankdev.io Development
    jobs:
    - deployment:
      environment: dev-K8s-sfihelv-kubeserver-d001
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo "FrankieDev.io Development Deploy after Build Artifacts"
            
            - checkout: self
              persistCredentials: true

            - bash: |
                git checkout cluster/development
                ls -la
              displayName: Checkout branch cluster/development

            - task: CopyFiles@2
              inputs:
                SourceFolder: $(Build.ArtifactStagingDirectory)
                Contents: |
                  base/**/*
                  overlays/development/**/*
                OverWrite: true
                TargetFolder: $(Build.SourcesDirectory)

            - bash: |
                git add .
                git commit -am"Deploying revision"
                git push

            


